export enum ServicesCategory {
  Consultation = "consultation",
  DuplexScan = "duplexScan", // Մագիստրալ անոթների դուպլեքս հետազոտություն
  Ultrasound = "ultraSound", // Ուլտրաձայնային հետազոտություն
  CardiacCare = "cardiacCare", // Սրտային խնամք
  PreventiveScreening = "preventiveScreening", // Տարեկան կանխարգելիչ բուժ․ զննում
}

export type ServiceType = {
  id: number;
  name: string;
  price: number;
  description?: string;
  category: ServicesCategory;
  doctorsList?: number[]; // List of doctor IDs associated with the service
  hideInServicesPage?: boolean; // Optional field to hide service in the services page
  hideInPriceListPage?: boolean; // Optional field to hide service in the priceList page
};

export interface CardI {
  service: ServiceType;
}

interface PriceListI {
  en: ServiceType[];
  am: ServiceType[];
  ru: ServiceType[];
}

export const categorizedServicesOrder = [
  ServicesCategory.Consultation,
  ServicesCategory.CardiacCare,
  ServicesCategory.Ultrasound,
  ServicesCategory.DuplexScan,
  ServicesCategory.PreventiveScreening, // is not visible
];

const cardioDoctorsIds = [1, 3, 7, 25, 4, 24, 6, 27, 8, 9];
const cardioDoctorsIdsConsultationTeam = [1, 3, 7, 25, 4, 24, 2, 6, 27, 8, 9];
const nursesIds = [19];

// Armenian service names used for all languages
// OLD ONE
// const services: ServiceType[] = [
//   {
//     id: 34,
//     name: "Սրտաբանի խորհրդատվություն",
//     price: 15000,
//     description: "",
//     category: ServicesCategory.Consultation,
//     doctorsList: cardioDoctorsIdsConsultationTeam,
//   },
//   {
//     id: 35,
//     name: "Սրտաբան-առիթմոլոգի խորհրդատվություն",
//     price: 15000,
//     description: "",
//     category: ServicesCategory.Consultation,
//     doctorsList: [1],
//   },
//   {
//     id: 36,
//     name: "Մանկական սրտաբանի խորհրդատվություն",
//     price: 15000,
//     description: "",
//     category: ServicesCategory.Consultation,
//     doctorsList: [5],
//   },
//   {
//     id: 37,
//     name: "Ինվազիվ մանկական սրտաբանի խորհրդատվություն",
//     price: 15000,
//     description: "",
//     category: ServicesCategory.Consultation,
//     doctorsList: [2],
//   },
//   {
//     id: 38,
//     name: "Սրտային անբավարարության մասնագետի խորհրդատվություն",
//     price: 15000,
//     description: "",
//     category: ServicesCategory.Consultation,
//     doctorsList: [1, 3, 24],
//   },
//   {
//     id: 39,
//     name: "Աղեստամոքսաբանի խորհրդատվություն",
//     price: 15000,
//     description: "",
//     category: ServicesCategory.Consultation,
//     doctorsList: [13],
//   },
//   {
//     id: 40,
//     name: "Ներզատաբանի խորհրդատվություն",
//     price: 15000,
//     description: "",
//     category: ServicesCategory.Consultation,
//     doctorsList: [11],
//   },
//   {
//     id: 41,
//     name: "Նյարդաբանի խորհրդատվություն",
//     price: 15000,
//     description: "",
//     category: ServicesCategory.Consultation,
//     doctorsList: [12],
//   },
//   {
//     id: 42,
//     name: "Թերապևտի խորհրդատվություն",
//     price: 15000,
//     description: "",
//     category: ServicesCategory.Consultation,
//     doctorsList: [13],
//   },
//   {
//     id: 43,
//     name: "Անոթային վիրաբույժի խորհրդատվություն",
//     price: 15000,
//     description: "",
//     category: ServicesCategory.Consultation,
//     doctorsList: [16],
//   },
//   {
//     id: 14,
//     name: "Հոգեբանական խորհրդատվություն",
//     price: 25000,
//     description: "",
//     category: ServicesCategory.Consultation,
//     doctorsList: [17],
//   },
//   {
//     id: 15,
//     name: "Հոգեբանական կրկնակի խորհրդատվություն",
//     price: 20000,
//     description: "",
//     category: ServicesCategory.Consultation,
//     doctorsList: [],
//     hideInServicesPage: true,
//   },
//   {
//     id: 1,
//     name: "Առողջ ապրելակերպի մասնագետի խորհրդատվություն",
//     price: 20000,
//     description: "",
//     category: ServicesCategory.Consultation,
//     doctorsList: [18],
//   },
//   // ######### ######### ######### ######### ######### ######### ######### #########
//   {
//     id: 9,
//     name: "ԷՍԳ, ԷխոՍԳ, սրտաբանի խորհրդատվություն",
//     price: 28000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     hideInServicesPage: true,
//     doctorsList: cardioDoctorsIdsConsultationTeam,
//   },
//   {
//     id: 8,
//     name: "ԷՍԳ – 12Ա",
//     price: 4000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     doctorsList: nursesIds,
//   },
//   {
//     id: 7,
//     name: "Էխոսրտագրություն մեծահասակի",
//     price: 13000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     doctorsList: cardioDoctorsIds,
//   },
//   {
//     id: 6,
//     name: "Էխոսրտագրություն մանկական",
//     price: 13000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     doctorsList: [5],
//   },
//   {
//     id: 32,
//     name: "Ֆետալ էխոՍԳ",
//     price: 20000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     doctorsList: [5],
//   },
//   {
//     id: 33,
//     name: "Ֆետալ էխոՍԳ + սրտաբանի խորհրդատվություն",
//     price: 30000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     hideInServicesPage: true,
//     doctorsList: [5],
//   },
//   {
//     id: 13,
//     name: "Կոնտրաստ ԷխոՍԳ (bubble study)",
//     price: 25000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     doctorsList: [5],
//   },
//   {
//     id: 12,
//     name: "Խորացված ԷխոՍԳ",
//     price: 25000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     doctorsList: cardioDoctorsIds,
//   },
//   {
//     id: 28,
//     name: "Սթրես ԷՍԳ",
//     price: 18000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     doctorsList: cardioDoctorsIds,
//   },
//   {
//     id: 47,
//     name: "Սթրես ԷխոՍԳ",
//     price: 22000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     doctorsList: cardioDoctorsIds,
//   },
//
//   {
//     id: 26,
//     name: "Սթրես ԷխոՍԳ + սրտաբանի խորհրդատվություն",
//     price: 32000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     hideInServicesPage: true,
//     doctorsList: cardioDoctorsIds,
//   },
//   {
//     id: 29,
//     name: "Սթրես ԷՍԳ + սրտաբանի խորհրդատվություն",
//     price: 28000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     hideInServicesPage: true,
//     doctorsList: cardioDoctorsIds,
//   },
//   // #################################################################################
//   {
//     id: 16,
//     name: "Հոլտեր քննություն 24 ժամ",
//     price: 22000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     hideInServicesPage: true,
//     doctorsList: cardioDoctorsIds,
//   },
//   {
//     id: 18,
//     name: "Հոլտեր քննություն 48 ժամ",
//     price: 33000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     hideInServicesPage: true,
//     doctorsList: cardioDoctorsIds,
//   },
//   {
//     id: 19,
//     name: "Հոլտեր քննություն 72 ժամ",
//     price: 45000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     hideInServicesPage: true,
//     doctorsList: cardioDoctorsIds,
//   },
//   {
//     id: 21,
//     name: "Հոլտեր քննություն մինչեւ 7 oր",
//     price: 60000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     hideInServicesPage: true,
//     doctorsList: cardioDoctorsIds,
//   },
//   {
//     id: 20,
//     name: "Հոլտեր քննություն մինչեւ 14 օր",
//     price: 99000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     hideInServicesPage: true,
//     doctorsList: cardioDoctorsIds,
//   },
//   {
//     id: 22,
//     name: "Հոլտեր քննություն մինչեւ մինչեւ 30 օր",
//     price: 160000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     hideInServicesPage: true,
//     doctorsList: cardioDoctorsIds,
//   },
//   {
//     id: 17,
//     name: "Հոլտեր քննություն 24 ժամ + սրտաբանի խորհրդատվություն",
//     price: 32000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     hideInServicesPage: true,
//     doctorsList: cardioDoctorsIds,
//   },
//   {
//     id: 53,
//     name: "Հոլտեր քննություն",
//     price: 0,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     hideInServicesPage: false,
//     hideInPriceListPage: true,
//     doctorsList: cardioDoctorsIds,
//   },
//   // #################################################################################
//   {
//     id: 5,
//     name: "ԶՃ ամբուլատոր մոնիտորինգ 24 ժամ",
//     price: 12000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     doctorsList: cardioDoctorsIds,
//   },
//   {
//     id: 31,
//     name: "Սրտի ռիթմավար սարքերի քննություն",
//     price: 12000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     doctorsList: [7],
//   },
//   {
//     id: 25,
//     name: "Ուլտրաձայնային հետազոտություն ",
//     price: 15000,
//     description: "",
//     category: ServicesCategory.Ultrasound,
//     doctorsList: [11, 14],
//   },
//   {
//     id: 48,
//     name: "Ուլտրաձայնային հետազոտություն (յուրաքանչյուր հաջորդ հավելյալ հատված)",
//     price: 12000,
//     description: "",
//     category: ServicesCategory.Ultrasound,
//     doctorsList: [11, 14],
//   },
//   {
//     id: 23,
//     name: "Մագիստրալ անոթների դուպլեքս հետազոտություն(1 հատված)",
//     price: 20000,
//     description: "",
//     category: ServicesCategory.DuplexScan,
//     doctorsList: [15],
//   },
//   {
//     id: 24,
//     name: "Մագիստրալ անոթների դուպլեքս հետազոտություն (յուրաքանչյուր հաջորդ հավելյալ հատված)",
//     price: 12000,
//     description: "",
//     category: ServicesCategory.DuplexScan,
//     doctorsList: [15],
//   },
//   {
//     id: 51,
//     name: "Սրտային անբավարարության ամբուլատոր խնամք (օրավարձային)",
//     price: 40000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     doctorsList: [1, 3, 24],
//   },
//   {
//     id: 4,
//     name: "Բժիշկ-մասնագետի հեռավար խորհրդատվություն",
//     price: 30000,
//     description: "",
//     category: ServicesCategory.Consultation,
//     doctorsList: [],
//   },
//   {
//     id: 2,
//     name: "Արտագնա հոլտեր քննություն 24 ժամ",
//     price: 35000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     doctorsList: [],
//   },
//   {
//     id: 52,
//     name: "Տարեկան կանխարգելիչ բուժ․ զննում",
//     price: 50000,
//     description: "",
//     category: ServicesCategory.PreventiveScreening,
//     doctorsList: [],
//     hideInServicesPage: true,
//     hideInPriceListPage: true,
//   },
//   {
//     id: 11,
//     name: "Իմպլանտացվող սրտի մոնիտորի իմպլանտացիա",
//     price: 1200000,
//     description: "",
//     category: ServicesCategory.CardiacCare,
//     doctorsList: [],
//   },
//   // #################################################################################
// ];

// Armenian service names used for all languages
const services: ServiceType[] = [
  {
    id: 1,
    name: "Էխոսրտագրություն մեծահասակի",
    price: 13000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [...cardioDoctorsIds],
  },
  {
    id: 2,
    name: "Էխոսրտագրություն մանկական",
    price: 13000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [5],
  },
  {
    id: 3,
    name: "Ֆետալ էխոՍԳ",
    price: 20000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [5],
  },
  {
    id: 4,
    name: "Կոնտրաստ ԷխոՍԳ (bubble study)",
    price: 25000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [5],
  },
  {
    id: 37,
    name: "Մագիստրալ անոթների դուպլեքս հետազոտություն",
    price: 20000,
    description: "",
    category: ServicesCategory.DuplexScan,
    doctorsList: [15],
  },
  {
    id: 38,
    name: "Ուլտրաձայնային հետազոտություն",
    price: 15000,
    description: "",
    category: ServicesCategory.Ultrasound,
    doctorsList: [11, 14],
  },
  {
    id: 5,
    name: "Սթրես էխոսրտագրություն",
    price: 22000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [...nursesIds],
  },
  {
    id: 6,
    name: "ԷՍԳ – 12Ա",
    price: 4000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [...nursesIds],
  },
  {
    id: 60,
    name: "Սկլերոթերապիա",
    price: 25000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [],
  },
  {
    id: 8,
    name: "Հոլտեր քննություն 24 ժամ",
    price: 22000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [...cardioDoctorsIds],
  },
  {
    id: 9,
    name: "Հոլտեր քննություն 48 ժամ",
    price: 33000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [...cardioDoctorsIds],
  },
  {
    id: 34,
    name: "Հոլտեր քննություն մինչև 7 oր",
    price: 60000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [...cardioDoctorsIds],
  },
  {
    id: 35,
    name: "Հոլտեր քննություն մինչև 14 օր",
    price: 99000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [...cardioDoctorsIds],
  },
  {
    id: 12,
    name: "Հոլտեր քննություն մինչև մինչև 30 օր",
    price: 160000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [...cardioDoctorsIds],
  },
  {
    id: 13,
    name: "ԶՃ ամբուլատոր մոնիտորինգ 24 ժամ",
    price: 12000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [...cardioDoctorsIds],
  },
  {
    id: 14,
    name: "Սրտի ռիթմավար սարքերի քննություն",
    price: 15000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [7],
  },
  {
    id: 15,
    name: "Սրտային անբավարարության ամբուլատոր խնամք",
    price: 10000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [1, 3, 24],
  },
  {
    id: 16,
    name: "Իմպլանտացվող սրտի մոնիտորի իմպլանտացիա",
    price: 1200000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [],
  },
  {
    id: 39,
    name: "Բժիշկ-մասնագետի խորհրդատվություն",
    price: 15000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [...cardioDoctorsIdsConsultationTeam],
  },
  {
    id: 41,
    name: "Բժիշկ-մասնագետի հեռավար խորհրդատվություն",
    price: 30000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [],
  },
  {
    id: 29,
    name: "Հոգեբանական խորհրդատվություն",
    price: 25000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [17],
  },
  {
    id: 30,
    name: "ԷՍԳ, ԷխոՍԳ, սրտաբանի խորհրդատվություն",
    price: 28000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [...cardioDoctorsIdsConsultationTeam],
  },
  {
    id: 32,
    name: "Սթրես ԷխոՍԳ + սրտաբանի խորհրդատվություն",
    price: 32000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [...cardioDoctorsIds],
  },
  {
    id: 42,
    name: "ԷՍԳ, ԷխոՍԳ, սրտաբանի խորհրդատվություն, 24ժ.Հոլտեր քննություն",
    price: 45000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [...cardioDoctorsIdsConsultationTeam],
  },
  {
    id: 43,
    name: "Մագիստրալ անոթների դուպլեքս հետազոտություն(յուրաքանչյուր հաջորդ հավելյալ հատված)",
    price: 12000,
    description: "",
    category: ServicesCategory.DuplexScan,
    doctorsList: [15],
  },
  {
    id: 44,
    name: "Արտագնա հոլտեր քննություն 24 ժամ",
    price: 35000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [...cardioDoctorsIds],
  },
  {
    id: 45,
    name: "Հոլտեր քննություն 24 ժամ  + սրտաբանի խորհրդատվություն",
    price: 32000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [...cardioDoctorsIds],
  },
  {
    id: 46,
    name: "Սթրես ԷՍԳ  + սրտաբանի խորհրդատվություն",
    price: 28000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [...cardioDoctorsIds],
  },
  {
    id: 47,
    name: "Ֆետալ էխոՍԳ + սրտաբանի խորհրդատվություն",
    price: 30000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [5],
  },
  {
    id: 51,
    name: "Կրկնակի հոգեբանական խորհրդատվություն",
    price: 20000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [17],
    hideInServicesPage: true,
  },
  {
    id: 54,
    name: "Հոլտեր քննություն 72 ժամ",
    price: 45000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [...cardioDoctorsIds],
  },
  {
    id: 55,
    name: "Առողջ ապրելակերպի հերթական խորհրդատվություն",
    price: 20000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [18],
  },
  {
    id: 56,
    name: "Խորացված ԷխոՍԳ",
    price: 25000,
    description: "",
    category: ServicesCategory.CardiacCare,
    doctorsList: [...cardioDoctorsIds],
  },
  {
    id: 63,
    name: "Մագիստրալ անոթների դուպլեքս հետազոտություն (4 հատված)",
    price: 56000,
    description: "",
    category: ServicesCategory.DuplexScan,
    doctorsList: [15],
  },
  {
    id: 64,
    name: "Ուլտրաձայնային հետազոտություն (2 հատված)",
    price: 20000,
    description: "",
    category: ServicesCategory.Ultrasound,
    doctorsList: [11, 14],
  },
  {
    id: 67,
    name: "Տ․Հովակիմյան Բժիշկ-մասնագետի խորհրդատվություն ",
    price: 32000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [1],
  },
  {
    id: 7,
    name: "Սթրես ԷՍԳ",
    price: 18000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [...cardioDoctorsIds],
  },
  {
    id: 66,
    name: "Թարգմանված տեղեկանքի տրամադրում",
    price: 30000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [],
  },
  {
    id: 62,
    name: "Մագիստրալ անոթների դուպլեքս հետազոտություն (3 հատված)",
    price: 44000,
    description: "",
    category: ServicesCategory.DuplexScan,
    doctorsList: [15],
  },
  {
    id: 57,
    name: "Ուլտրաձայնային հետազոտություն (յուրաքանչյուր հաջորդ հավելյալ հատված)",
    price: 5000,
    description: "",
    category: ServicesCategory.Ultrasound,
    doctorsList: [11, 14],
  },
  {
    id: 65,
    name: "Ուլտրաձայնային հետազոտություն (3 հատված)",
    price: 25000,
    description: "",
    category: ServicesCategory.Ultrasound,
    doctorsList: [11, 14],
  },
  {
    id: 68,
    name: "Տաթևիկ Հովակիմյան խորհրդատվություն",
    price: 20000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [1],
  },
  {
    id: 69,
    name: "Արփինե Սիմոնյան խորհրդատվություն",
    price: 20000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [13],
  },
  {
    id: 70,
    name: "Կատարինե Վարդանյան խորհրդատվություն",
    price: 15000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [3],
  },
  {
    id: 71,
    name: "Մարիամ Մինասյան խորհրդատվություն",
    price: 15000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [4],
  },
  {
    id: 72,
    name: "Աննա Գևորգյան խորհրդատվություն",
    price: 15000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [],
  },
  {
    id: 73,
    name: "Մարիամ Հովակիմյան խորհրդատվություն",
    price: 15000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [10],
  },
  {
    id: 74,
    name: "Նադեժդա Իսկանդարյան խորհրդատվություն",
    price: 15000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [25],
  },
  {
    id: 75,
    name: "Գևորգ Պետրոսյան խորհրդատվություն",
    price: 15000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [7],
  },
  {
    id: 76,
    name: "Իզաբելլա Բարեկյան խորհրդատվություն",
    price: 15000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [9],
  },
  {
    id: 77,
    name: "Մերի Պապիկյան խորհրդատվություն",
    price: 15000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [24],
  },
  {
    id: 78,
    name: "Տաթևիկ Սիմոնյան խորհրդատվություն",
    price: 15000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [5],
  },
  {
    id: 79,
    name: "Քնարիկ Բադեյան խորհրդատվություն",
    price: 15000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [11],
  },
  {
    id: 80,
    name: "Անահիտ Ոսկանյան խորհրդատվություն",
    price: 15000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [12],
  },
  {
    id: 81,
    name: "Կարինե Մկրտչյան խորհրդատվություն",
    price: 15000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [14],
  },
  {
    id: 82,
    name: "Աստղիկ Ավետիքյան խորհրդատվություն",
    price: 15000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [15],
  },
  {
    id: 83,
    name: "Աղունիկ Զաքարյան խորհրդատվություն",
    price: 15000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [16],
  },
  {
    id: 84,
    name: "Արթուր Հակոբյան խորհրդատվություն",
    price: 15000,
    description: "",
    category: ServicesCategory.Consultation,
    doctorsList: [23],
  },
];

// Generate the price lists for each language using the same service names
export const priceListData: PriceListI = {
  en: services,
  am: services,
  ru: services,
};
