import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import React from "react";
import ScrollToTop from "~/app/_components/ScrollToTop";
import NavigationBar from "~/app/_components/NavigationBar";
import { Providers } from "~/app/providers";
import Footer from "~/app/_components/Footer";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`bg-[#FCFCFC] dark:bg-black ${GeistSans.variable} flex flex-col`}
      >
        <Providers>
          <NavigationBar />
          <div className="w-full">{children}</div>
          <Footer />
          <ScrollToTop />
        </Providers>
      </body>
    </html>
  );
}
