import { defineType, defineField } from 'sanity';

export default defineType({
  name: 'staff',
  title: 'Staff Members',
  type: 'document',
  fields: [
    defineField({
      name: 'id',
      title: 'Staff ID',
      type: 'number',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'name',
      title: 'Name',
      type: 'object',
      fields: [
        { name: 'am', title: 'Armenian', type: 'string' },
        { name: 'en', title: 'English', type: 'string' },
        { name: 'ru', title: 'Russian', type: 'string' },
      ],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'role',
      title: 'Role',
      type: 'object',
      fields: [
        { name: 'am', title: 'Armenian', type: 'string' },
        { name: 'en', title: 'English', type: 'string' },
        { name: 'ru', title: 'Russian', type: 'string' },
      ],
    }),
    defineField({
      name: 'image',
      title: 'Profile Image',
      type: 'image',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      options: {
        list: [
          { title: 'Medical', value: 'medical' },
          { title: 'Nursing', value: 'nursing' },
          { title: 'Administrative', value: 'administrative' },
        ],
      },
    }),
    defineField({
      name: 'visibility',
      title: 'Visibility',
      type: 'object',
      fields: [
        { name: 'showInStaffPage', title: 'Show in Staff Page', type: 'boolean', initialValue: true },
        { name: 'showInLandingPage', title: 'Show in Landing Page', type: 'boolean', initialValue: false },
      ],
    }),
    defineField({
      name: 'personalInfo',
      title: 'Personal Information',
      type: 'object',
      fields: [
        {
          name: 'flags',
          title: 'Display Flags',
          type: 'object',
          fields: [
            { name: 'showBio', title: 'Show Biography', type: 'boolean', initialValue: false },
            { name: 'showExperience', title: 'Show Experience', type: 'boolean', initialValue: false },
            { name: 'showEducation', title: 'Show Education', type: 'boolean', initialValue: false },
            { name: 'showPublications', title: 'Show Publications', type: 'boolean', initialValue: false },
            { name: 'showAchievements', title: 'Show Achievements', type: 'boolean', initialValue: false },
            { name: 'showLanguages', title: 'Show Languages', type: 'boolean', initialValue: false },
            { name: 'showContact', title: 'Show Contact', type: 'boolean', initialValue: false },
            { name: 'showSocial', title: 'Show Social Media', type: 'boolean', initialValue: false },
            { name: 'showSpecialty', title: 'Show Specialty', type: 'boolean', initialValue: false },
          ],
        },
        {
          name: 'am',
          title: 'Armenian Content',
          type: 'object',
          fields: [
            { name: 'bio', title: 'Biography', type: 'text' },
            { name: 'specialty', title: 'Specialty', type: 'string' },
            {
              name: 'experience',
              title: 'Experience',
              type: 'array',
              of: [{ type: 'string' }],
            },
            {
              name: 'education',
              title: 'Education',
              type: 'array',
              of: [{ type: 'string' }],
            },
            {
              name: 'publications',
              title: 'Publications',
              type: 'array',
              of: [{ type: 'string' }],
            },
            {
              name: 'achievements',
              title: 'Achievements',
              type: 'array',
              of: [{ type: 'string' }],
            },
            {
              name: 'languages',
              title: 'Languages',
              type: 'array',
              of: [{ type: 'string' }],
            },
            { name: 'email', title: 'Email', type: 'string' },
            { name: 'phone', title: 'Phone', type: 'string' },
            { name: 'facebook', title: 'Facebook', type: 'url' },
            { name: 'linkedin', title: 'LinkedIn', type: 'url' },
            { name: 'twitter', title: 'Twitter', type: 'url' },
          ],
        },
        {
          name: 'en',
          title: 'English Content',
          type: 'object',
          fields: [
            { name: 'bio', title: 'Biography', type: 'text' },
            { name: 'specialty', title: 'Specialty', type: 'string' },
            {
              name: 'experience',
              title: 'Experience',
              type: 'array',
              of: [{ type: 'string' }],
            },
            {
              name: 'education',
              title: 'Education',
              type: 'array',
              of: [{ type: 'string' }],
            },
            {
              name: 'publications',
              title: 'Publications',
              type: 'array',
              of: [{ type: 'string' }],
            },
            {
              name: 'achievements',
              title: 'Achievements',
              type: 'array',
              of: [{ type: 'string' }],
            },
            {
              name: 'languages',
              title: 'Languages',
              type: 'array',
              of: [{ type: 'string' }],
            },
            { name: 'email', title: 'Email', type: 'string' },
            { name: 'phone', title: 'Phone', type: 'string' },
            { name: 'facebook', title: 'Facebook', type: 'url' },
            { name: 'linkedin', title: 'LinkedIn', type: 'url' },
            { name: 'twitter', title: 'Twitter', type: 'url' },
          ],
        },
        {
          name: 'ru',
          title: 'Russian Content',
          type: 'object',
          fields: [
            { name: 'bio', title: 'Biography', type: 'text' },
            { name: 'specialty', title: 'Specialty', type: 'string' },
            {
              name: 'experience',
              title: 'Experience',
              type: 'array',
              of: [{ type: 'string' }],
            },
            {
              name: 'education',
              title: 'Education',
              type: 'array',
              of: [{ type: 'string' }],
            },
            {
              name: 'publications',
              title: 'Publications',
              type: 'array',
              of: [{ type: 'string' }],
            },
            {
              name: 'achievements',
              title: 'Achievements',
              type: 'array',
              of: [{ type: 'string' }],
            },
            {
              name: 'languages',
              title: 'Languages',
              type: 'array',
              of: [{ type: 'string' }],
            },
            { name: 'email', title: 'Email', type: 'string' },
            { name: 'phone', title: 'Phone', type: 'string' },
            { name: 'facebook', title: 'Facebook', type: 'url' },
            { name: 'linkedin', title: 'LinkedIn', type: 'url' },
            { name: 'twitter', title: 'Twitter', type: 'url' },
          ],
        },
      ],
    }),
  ],
  preview: {
    select: {
      title: 'name.en',
      subtitle: 'role.en',
      media: 'image',
    },
  },
});
